name: Create Jira Issue  
on:
  workflow_call:
    inputs:
      title:
        description: "title for the issue, it will be concatenated with the app/releasetag"
        type: string
        required: true
        default: ' '
      value1:
        description: "a formatted string for the body of the issue, each fieldValue will be line separated"
        type: string
        required: true
        default: ' '
      value2:
        type: string
        required: false
        default: ' '
      value3:
        type: string
        required: false
        default: ' '
      value4:
        type: string
        required: false
        default: ' '
      value5:
        type: string
        required: false
        default: ' '
      projectKey:
        default: ''
        required: true
        description: 'Project key in JIRA'
        type: string  
      releaseTag:
        default: 'not specified'
        required: false
        description: 'Semantic Version from ReleaseDrafter'
        type: string
    secrets:
      JIRA_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true
    
jobs:
  createJiraIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue via API
        shell: python
        run: | 
          import requests
          from requests.auth import HTTPBasicAuth
          import json

          auth = HTTPBasicAuth("${{ secrets.JIRA_EMAIL }}", "${{ secrets.JIRA_API_TOKEN }}")
          url = "https://wahbejira.atlassian.net/rest/api/3/issue"
          headers = {
              "Accept": "application/json",
              "Content-Type": "application/json"
          }
          data = json.dumps( 
               {
                "fields": {
                  "project": {
                  "key": "${{inputs.projectKey}}"
                },
                "summary": "${{inputs.title}}" + " - " + "${{inputs.releaseTag}}",
                "description": {
                  "type": "doc",
                  "version": 1,
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                          "text": "${{inputs.value1}}" + "\n" + "${{inputs.value2}}" + "\n" +  "${{inputs.value3}}" + "\n" + "${{inputs.value4}}" + "\n" "${{inputs.value5}}"
                        }
                      ]
                    }
                  ]
                },
                "issuetype": {
                  "name": "Task"
                }
              }
            })

          print(data)

          response = requests.request(
              "POST",
              url,
              headers=headers,
              data=data,
              auth=auth
          )

          print(response.text)
