name: CreateCronJob

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string
      GithubRunnerGroupName:
        default: 'linux-hosting-nonprod'
        required: false
        type: string
      AroProjectName:
        required: true
        type: string
      CronJobName:
        required: true
        type: string
      CronJobUrl:
        required: true
        type: string 
      CronJobSchedule:
        default: '*/60 * * * *'
        required: false
        type: string
      CurlRequestMethod:
        default: 'GET'
        required: false
        type: string
    secrets:
      OPENSHIFT_SERVER_URL:
        required: true
      OPENSHIFT_TOKEN:
        required: true

jobs:
  deploy:
    environment: ${{ inputs.Environment }}
    runs-on: ${{ inputs.GithubRunnerGroupName }}

    steps:
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ inputs.AroProjectName }}

      - name: Delete cron job if it already exists
        run: >
          oc delete cronjob/${{ inputs.CronJobName }}
        continue-on-error: true

      - name: Create the cron job
        run: >
          oc create cronjob ${{ inputs.CronJobName }} --image=rhel7 --schedule='${{ inputs.CronJobSchedule }}' -- curl -X ${{ inputs.CurlRequestMethod }} -kvs ${{ inputs.CronJobUrl }}