name: DotNet Accessibility Testing

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      repoName:
        type: string
        required: true
        description: The name of the repository to run dotnet tests against
      suiteName:
        type: string
        required: true
        description: The name of the test suite to run
      outputDir:
        type: string
        required: false
        description: The directory to output the test results to
      uiTest:
        type: boolean
        required: false
        description: Whether or not to run UI tests
      GithubRunnerGroupName:
        type: string
        default: 'linux-hosting-nonprod'
        required: false
      environment:
        type: string
        default: 'test'
        required: false
      DotNetVersion:
        default: '6.0.x'
        required: false
        type: string
      workingDir:
        type: string
        required: false
        description: The directory to run the test results to
        
    secrets:
      repoToken:
        required: true
      
      
jobs:
  runAccessibilityTests:
    name: Run Accessibility Tests
    runs-on: ${{ inputs.GithubRunnerGroupName }}

    steps:
    - name: Download Test Repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repoName }}
        token: ${{ secrets.repoToken }}
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.DotNetVersion }}
        
    - name: Install dependencies
      run: dotnet restore  

    - name: Make TestResults directory
      run: mkdir ${{ github.workspace }}/${{ inputs.suiteName }}/TestResults
      #working-directory: ${{ github.workspace }}/${{ inputs.suiteName }}
             
    - name: Run AccessibilityTests
      run: |
        dotnet test -c Release "-l:trx;LogFileName=TestOutput.xml"
       
       
        
    #- name: List files in the repository
      #run: |
        #ls ${{ github.workspace }}/${{ inputs.suiteName }}/TestResults    
        
    - name: Upload Test Results Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:    
        name: NUnitReport    
        path: ${{ github.workspace }}/${{ inputs.suiteName }}/TestResults/TestOutput.xml
            
    - name: Upload Findings
      uses: actions/upload-artifact@v3.1.0
      with:    
        name: ADAFindings    
        path: ${{ github.workspace }}/${{ inputs.suiteName }}/bin/Release/net6.0/concerns.json


