name: DotNetApiBuild

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      GithubRunnerGroupName:
        default: 'ubuntu-latest'
        required: false
        type: string
      DotNetVersion:
        default: '6.0.x'
        required: false
        type: string
      ContainerTag:
        default: 'api:latest'
        required: false
        type: string
      DockerFilePath:
        default: './Api/Dockerfile'
        required: false
        type: string
      BuildArtifactRetentionDays:
        default: 3
        required: false
        type: number
    secrets:
      GH_PACKAGES_TOKEN:
        required: true
jobs:
  build:
    runs-on: ${{ inputs.GithubRunnerGroupName }}

    steps:
    - uses: actions/checkout@v2

    # Setup .net
    - name: Setup .NET with nuget.config
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.DotNetVersion }}
        config-file: './nuget.config'   

    # Setup docker build X so that we can build and export the image to a tar file
    - name: 'Set up docker build x'
      uses: docker/setup-buildx-action@v1
    
    - name: 'Tmp Before build'
      run: ls -la /tmp
     
    # Build docker image and export to a .tar file
    - name: Build and export image to .tar file
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.DockerFilePath }}
        tags: ${{ inputs.ContainerTag }}, api:${{github.run_number}}, api:${{github.sha}}
        build-args: GH_PACKAGES_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }}
        
        outputs: type=docker,dest=/tmp/image.tar
        
    - name: 'Tmp After build'
      run: ls -la /tmp
    
    # Upload the image tar file so that we can use it to deploy to multiple environments
    - name: Upload image .tar file to Github artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: '/tmp/image.tar'
        retention-days: ${{ inputs.BuildArtifactRetentionDays }}
