name: Grab release tag as an output

on:
  workflow_call:
     inputs:
      repoName:
        type: string
        required: true
        description: The name of the repository to run dotnet tests against
     outputs: 
        releaseTag: 
           value: ${{ jobs.getReleaseTag.outputs.releaseTag }}
           
   
jobs:
  getReleaseTag:
    runs-on: ubuntu-latest
    outputs:
       releaseTag: ${{ steps.get_tag.outputs.tagName }}
       
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get release tag via GH CLI
        id: get_tag
        run: |
          tag=$(gh api https://api.github.com/repos/${{ inputs.repoName }}/releases/latest | jq -r  .tag_name)
          echo "tagName=$tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
         
         #tag=$(gh api https://api.github.com/repos/${{ inputs.repoName }}/releases/latest | jq -r  .tag_name)
         
      - name: Echo output
        run: echo ${{ steps.get_tag.outputs.tagName }} 
        
      - name: Get major version num and update tag
        run: |
         VERSION=${GITHUB_REF#refs/tags/}
         echo "VERSION=$VERSION" 
