---
####################################
####################################
## Draft releases on Push to main ##
####################################
####################################
name: Release Drafter

###########################
# Start on call #
###########################
on:
  workflow_call:
    

#################
# Start the job #
#################
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main" and Release published
      - uses: release-drafter/release-drafter@v5
        with:
           publish: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
